/**:
  ros__parameters:
    camera_info_url: package://rm_bringup/config/camera_info.yaml
    exposure_time: 2500
    gain: 15.0
  #  resolution_width: 1624
  #  resolution_height: 1240
    resolution_width: 1480
    resolution_height: 720
    offsetX: 0
    offsetY: 0
    camera_name: "daheng"
    recording: false    #是否录制
